apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-recommender-api-deployment
  labels:
    app: saga-recommender-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: saga-recommender-api
  template:
    metadata:
      labels:
        app: saga-recommender-api
    spec:
      containers:
        - name: saga-recommender-api
          image: {{ .Values.deployment.image }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user-pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-endpoint
          ports:
          - containerPort: {{ .Values.deployment.port }}